import numpy as np
import arepy as apy
import re

class config():
    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        True

    def __init__(self,fileName=None,show=False,notes=False):
        self.groups = [
            {'id':0, 'name':"Basic operation mode of code",
             'params':['NTYPES','PERIODIC','TWODIMS','AXISYMMETRY','ONEDIMS','LONG_X','LONG_Y','LONG_Z','REFLECTIVE_X',
                       'REFLECTIVE_Y','REFLECTIVE_Z','MHD','MHD_DONT_PRINT_BMAGSUM','MHD_CT','MHD_CT_IC',
                       'MHD_CT_PERTURB_POSITIONS','MHD_DIVBCLEANING','MHD_POWELL','MHD_POWELL_LIMIT_TIMESTEP','MHD_SEEDFIELD',
                       'MHD_SEEDPSPEC','MHD_THERMAL_ENERGY_SWITCH','COOLING','UVB_SELF_SHIELDING','USE_SFR','QUICK_LYALPHA',
                       'QUICK_LYALPHA_LATETIMEONLY','SFR_KEEP_CELLS','GAMMA','ISOTHERM_EQS','USE_ENTROPY_FOR_COLD_FLOWS',
                       'ENTROPY_MACH_THRESHOLD','PREHEATING','NOHYDRO','SPECIAL_RELATIVITY','SPECIAL_RELATIVITY_HLLC',
                       'SR_HLLC_ZERO_COMPVEL','GENERAL_RELATIVITY','METRIC_TYPE','ATMOSPHERE_GENERAL_RELATIVITY',
                       'ADIABATIC_GENERAL_RELATIVITY']},
            {'id':1, 'name':"NON-IDEAL MHD",
             'params':['NON_IDEAL_MHD','OHMIC_DIFFUSION','IMPLICIT_OHMIC_DIFFUSION','ONLY_OHMIC_DIFFUSION']},
            {'id':2, 'name':"COSMIC RAYS",
             'params':['DIFFUSION','COSMIC_RAYS','COSMIC_RAYS_COOLING','COSMIC_RAYS_ALFVEN_COOLING','COSMIC_RAYS_STREAMING',
                       'COSMIC_RAYS_STREAMING_ANISOTROPIC','COSMIC_RAYS_DIFFUSION','COSMIC_RAYS_DIFFUSION_CONSTANT_TIMESTEP',
                       'COSMIC_RAYS_DIFFUSION_GLOBAL_TIMESTEP','COSMIC_RAYS_DIFFUSION_EXPLICIT',
                       'COSMIC_RAYS_DIFFUSION_FULL_NORMAL_GRADIENT','COSMIC_RAYS_DIFFUSION_ALWAYS_USE_PRECONDITIONER',
                       'COSMIC_RAYS_DIFFUSION_ANISOTROPIC','COSMIC_RAYS_DIFFUSION_LIMITER','COSMIC_RAYS_DIFFUSION_OLD',
                       'COSMIC_RAYS_SN_INJECTION','COSMIC_RAYS_SHOCK_ACCELERATION','COSMIC_RAYS_IN_ICS',
                       'COSMIC_RAYS_MAGNETIC_OBLIQUITY','OUTPUT_CR_PRESSURE_GRADIENT']},
            {'id':3, 'name':"MPI/Threading Hybrid",
             'params':['NUM_THREADS','IMPOSE_PINNING','IMPOSE_PINNING_OVERRIDE_MODE','GENERIC_ASYNC']},
            {'id':4, 'name':"Mesh Type",
             'params':['AMR','VORONOI']},
            {'id':5, 'name':"Riemann solver",
             'params':['VARIABLE_GAMMA','RIEMANN_HLL','RIEMANN_HLLC','RIEMANN_ROSUNOV','RIEMANN_HLLD','RIEMANN_GAMMA',
                       'AMR_CONNECTIONS','AMR_GRADIENTS','AMR_REDUCE_DOMAIN_DECOMPOISTION']},
            {'id':6, 'name':"Reconstruction",
             'params':['TVD_SLOPE_LIMITER','TVD_SLOPE_LIMITER_VANLEER','TVD_SLOPE_LIMITER_SUPERBEE','TVD_SLOPE_LIMITER_ALBADA',
                       'TVD_SLOPE_LIMITER_MINBEE','GRADIENT_LIMITER_DUFFELL','DISABLE_TIME_EXTRAPOLATION',
                       'DISABLE_SPATIAL_EXTRAPOLATION','NO_SCALAR_GRADIENTS','GRADIENTS_GREEN_GAUSS']},
            {'id':7, 'name':"Mesh motion and regularization",
             'params':['VORONOI_STATIC_MESH','VORONOI_STATIC_MESH_DO_DOMAIN_DECOMPOSITION','REGULARIZE_MESH_CM_DRIFT',
                       'REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED','REGULARIZE_MESH_FACE_ANGLE','REGULARIZE_MESH_OPTIMAL',
                       'OUTPUT_MESH_FACE_ANGLE','CALCULATE_VERTEX_VELOCITY_DIVERGENCE','STICKY_POINTS_ON_REFLECTIVE_SURFACE']},
            {'id':8, 'name':"Time integration options",
             'params':['FORCE_EQUAL_TIMESTEPS','TREE_BASED_TIMESTEPS','DECOUPLE_TIMESTEPS','MUSCL_HANCOCK',
                       'RUNGE_KUTTA_FULL_UPDATE']},
            {'id':9, 'name':"Direct Volume Raycast Rendering ",
             'params':['DVR_RENDER','DVR_RENDER_SMOOTH','DVR_RENDER_ORTHOGONAL','DVR_NUM_FIELDS','DVR_STAY_IN_BOX']},
            {'id':10, 'name':"Image generation",
             'params':['VORONOI_MESHOUTPUT','VORONOI_IMAGES_FOREACHSNAPSHOT','VORONOI_FREQUENT_IMAGES',
                       'VORONOI_FIELD_DUMP_PIXELS_X','VORONOI_FIELD_DUMP_PIXELS_Y','VORONOI_VELOCITY_FIELD_2D',
                       'VORONOI_FIELD_COMPENSATE_VX','VORONOI_FIELD_COMPENSATE_VY','VORONOI_NEW_IMAGE','VORONOI_PROJ_TEMP',
                       'VORONOI_PROJ','VORONOI_MULTIPLE_PROJECTIONS','VORONOI_NOGRADS']},
            {'id':11, 'name':"Refinement and derefinement",
             'params':['REFINEMENT_SPLIT_CELLS','REFINEMENT_MERGE_CELLS','REFINEMENT_MERGE_PAIRS','REFINEMENT_VOLUME_LIMIT',
                       'REFINEMENT_HIGH_RES_GAS','REFINEMENT_AROUND_BH','DEREFINE_ONLY_DENSE_GAS','NODEREFINE_BACKGROUND_GRID',
                       'DEREFINE_GENTLY','OPTIMIZE_MESH_MEMORY_FOR_REFINEMENT','REFINEMENT_AROUND_DM']},
            {'id':12, 'name':"Mesh-relaxing or mesh-adding (this will not carry out a simulation)",
             'params':['MESHRELAX','MESHRELAX_DENSITY_IN_INPUT','ADDBACKGROUNDGRID','AMR_REMAP']},
            {'id':13, 'name':"Gravity treatment",
             'params':['SELFGRAVITY','VALPOTENTIAL','HIERARCHICAL_GRAVITY','CELL_CENTER_GRAVITY','NO_GAS_SELFGRAVITY',
                       'GRAVITY_NOT_PERIODIC','GRAVITY_TALLBOX','NO_SELFGRAVITY_TYPE','ALLOW_DIRECT_SUMMATION',
                       'DIRECT_SUMMATION_THRESHOLD','EXACT_GRAVITY_FOR_PARTICLE_TYPE','EXTERNALGRAVITY','EXTERNALGY',
                       'EXTERNALDISKPOTENTIAL','EXTERNALSHEARBOX','EXTERNALSHEARBOX_KSRATE_RANDOM',
                       'EXTERNALSHEARBOX_KSRATE_UPDATE_PARAM','ENFORCE_JEANS_STABILITY_OF_CELLS_EEOS',
                       'ENFORCE_JEANS_STABILITY_OF_CELLS','EVALPOTENTIAL','EXTERNALSHEETY','COMPUTE_POTENTIAL_ENERGY',
                       'RANDOMIZE_DOMAINCENTER','DO_NOT_RANDOMIZE_DOMAINCENTER']},
            {'id':14, 'name':"Gravity softening",
             'params':['NSOFTTYPES','MULTIPLE_NODE_SOFTENING','INDIVIDUAL_GRAVITY_SOFTENING','ADAPTIVE_HYDRO_SOFTENING',
                       'NSOFTTYPES_HYDRO']},
            {'id':15, 'name':"TreePM Options",
             'params':['PMGRID','ASMTH','RCUT','PLACEHIGHRESREGION','ENLARGEREGION','GRIDBOOST','ONLY_PM','FFT_COLUMN_BASED',
                       'PM_ZOOM_OPTIMIZED']},
            {'id':16, 'name':"Things that are always recommended",
             'params':['AUTO_SWAP_ENDIAN_READIC','CHUNKING']},
            {'id':17, 'name':"Single/Double Precision",
             'params':['DOUBLEPRECISION','DOUBLEPRECISION_FFTW','OUTPUT_IN_DOUBLEPRECISION','INPUT_IN_DOUBLEPRECISION',
                       'OUTPUT_COORDINATES_IN_DOUBLEPRECISION','NGB_TREE_DOUBLEPRECISION']},
            {'id':18, 'name':"On the fly FOF groupfinder ",
             'params':['FOF','FOF_PRIMARY_LINK_TYPES','FOF_SECONDARY_LINK_TYPES','FOF_SECONDARY_LINK_TARGET_TYPES',
                       'FOF_GROUP_MIN_LEN','FOF_LINKLENGTH','FOF_FUZZ_SORT_BY_NEAREST_GROUP','FOF_STOREIDS',
                       'USE_AREPO_FOF_WITH_GADGET_FIX','ADD_GROUP_PROPERTIES']},
            {'id':19, 'name':"Subfind",
             'params':['SUBFIND','SAVE_HSML_IN_SNAPSHOT','SUBFIND_MEASURE_H2MASS','SUBFIND_CALC_MORE',
                       'SUBFIND_EXTENDED_PROPERTIES']},
            {'id':20, 'name':"SFR/feedback model",
             'params':['METALS','MIN_METALLICITY_ON_STARTUP','STELLARAGE','SOFTEREQS','MODIFIED_EOS','SLOW_RELAX_TO_EOS']},
            {'id':21, 'name':"AGN stuff",
             'params':['BLACK_HOLES','BH_THERMALFEEDBACK','BH_THERMALFEEDBACK_ACC','BH_NF_RADIO','DRAINGAS',
                       'BH_EXACT_INTEGRATION','BH_BONDI_DEFAULT','BH_BONDI_DENSITY','BH_BONDI_CAPTURE','BH_BONDI_DISK_VORTICITY',
                       'BH_DO_NOT_PREVENT_MERGERS','BH_USE_GASVEL_IN_BONDI','BH_USE_ALFVEN_SPEED_IN_BONDI','MASSIVE_SEEDS',
                       'MASSIVE_SEEDS_MERGER','BH_NEW_CENTERING','BH_FRICTION','BH_FRICTION_AGGRESSIVE',
                       'BH_HARMONIC_OSCILLATOR_FORCE','BH_DRAG','REPOSITION_ON_POTMIN','BH_PRESSURE_CRITERION',
                       'BH_RELATIVE_NGB_DEVIATION','OUTPUT_BLACK_HOLE_TIMESTEP']},
            {'id':22, 'name':"other AGN stuff",
             'params':['UNIFIED_FEEDBACK','BH_BUBBLES','BH_MAGNETIC_BUBBLES','BH_MAGNETIC_DIPOLAR_BUBBLES','BH_ADIOS_WIND',
                       'BH_ADIOS_DENS_DEP_EFFICIANCY','BH_ADIOS_WIND_WITH_QUASARTHRESHOLD',
                       'BH_ADIOS_WIND_WITH_VARIABLE_QUASARTHRESHOLD','BH_ADIOS_WIND_DIRECTIONAL','BH_ADIOS_RANDOMIZED',
                       'BH_ADIOS_ONLY_ABOVE_MINIMUM_DENSITY','BH_CONTINOUS_MODE_SWITCH']},
            {'id':23, 'name':"Black Hole Refinement and Bipolar Options",
             'params':['REFINEMENT_AROUND_BH_FIXED','SUPPRESS_SF_IN_REFINEMENT_REGION','BH_BIPOLAR_FEEDBACK']},
            {'id':24, 'name':"Passive Tracers",
             'params':['TRACER_FIELD','TRACER_PARTICLE','TRACER_MC','TRACER_MC_CHECKS','GENERATE_TRACER_PARTICLE_IN_ICS',
                       'GENERATE_TRACER_MC_IN_ICS','TRACER_PART_NUM_FLUID_QUANTITIES','TRACER_PART_STORE_WHAT',
                       'TRACER_MC_NUM_FLUID_QUANTITIES','TRACER_MC_STORE_WHAT','TRACER_NO_RESET_EACH_SNAP','TRACER_MC_SKIPLOAD',
                       'FOF_DISABLE_SNAP_REWRITE','TRACER_TRAJECTORY','TRACER_TRAJECTORY_GENERATE']},
            {'id':25, 'name':"Things for special behaviour",
             'params':['READ_DM_AS_GAS','NO_ID_UNIQUE_CHECK','RUNNING_SAFETY_FILE','LOAD_TYPES','READ_COORDINATES_IN_DOUBLE',
                       'IDS_OFFSET','TILE_ICS','COMBINETYPES','MULTIPLE_RESTARTS','TOLERATE_WRITE_ERROR','OPTIMIZE_MEMORY_USAGE',
                       'SUBBOX_SNAPSHOTS','PROCESS_TIMES_OF_OUTPUTLIST','EXTENDED_GHOST_SEARCH','DOUBLE_STENCIL',
                       'TETRA_INDEX_IN_FACE','VORONOI_DYNAMIC_UPDATE','COFFEE_PROBLEM','NOH_PROBLEM','SHIFT_BY_HALF_BOX',
                       'DISABLE_VELOCITY_CSND_SLOPE_LIMITING','NO_MPI_IN_PLACE','NO_ISEND_IRECV_IN_DOMAIN',
                       'FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG','USE_MPIALLTOALLV_IN_DOMAINDECOMP','MPI_HYPERCUBE_ALLGATHERV',
                       'MPISENDRECV_CHECKSUM','NOTREERND','ENLARGE_DYNAMIC_RANGE_IN_TIME','NOSTOP_WHEN_BELOW_MINTIMESTEP',
                       'DO_NOT_CREATE_STAR_PARTICLES','DMPIC','ALLOWEXTRAPARAMS','RADIATIVE_RATES',
                       'FIX_SPH_PARTICLES_AT_IDENTICAL_COORDINATES','VEL_POWERSPEC','ADJ_BOX_POWERSPEC',
                       'DISABLE_OPTIMIZE_DOMAIN_MAPPING','RECOMPUTE_POTENTIAL_IN_SNAPSHOT','CUDA','CUDA_INSTRUMENT','USE_DSDE',
                       'USE_NBC_FOR_IBARRIER','HUGEPAGES','DETAILEDTIMINGS','PERFORMANCE_TEST_SPARSE_MPI_ALLTOALL',
                       'TIMESTEP_OUTPUT_LIMIT']},
            {'id':26, 'name':"Output/Input options",
             'params':['UPDATE_GRADIENTS_FOR_OUTPUT','REDUCE_FLUSH','OUTPUT_REFBHCOUNTER','OUTPUT_EVERY_STEP','GODUNOV_STATS',
                       'OUTPUT_CPU_CSV','OUTPUT_TASK','OUTPUT_TIMEBIN_HYDRO','OUTPUT_PRESSURE_GRADIENT','OUTPUT_DENSITY_GRADIENT',
                       'OUTPUT_VELOCITY_GRADIENT','OUTPUT_BFIELD_GRADIENT','OUTPUT_VERTEX_VELOCITY',
                       'OUTPUT_VERTEX_VELOCITY_DIVERGENCE','OUTPUT_VOLUME','OUTPUT_CENTER_OF_MASS','OUTPUT_SURFACE_AREA',
                       'OUTPUT_PRESSURE','OUTPUTPOTENTIAL','OUTPUTACCELERATION','OUTPUTTIMESTEP','OUTPUT_SOFTENINGS',
                       'OUTPUTGRAVINTERACTIONS','HAVE_HDF5','HDF5_FILTERS','OUTPUT_XDMF','OUTPUTCOOLRATE','OUTPUT_DIVVEL',
                       'OUTPUT_CURLVEL','OUTPUT_COOLHEAT','OUTPUT_VORTICITY','OUTPUT_CELL_SPIN','MEASURE_DISSIPATION_RATE',
                       'OUTPUT_MACHNUM','OUTPUT_TASK']},
            {'id':27, 'name':"Testing and Debugging options",
             'params':['DEBUG','DEBUG_ENABLE_FPU_EXCEPTIONS','CHECKSUM_DEBUG','RESTART_DEBUG','VERBOSE','HOST_MEMORY_REPORTING',
                       'VTUNE_INSTRUMENT','FORCETEST','FORCETEST_TESTFORCELAW']},
            {'id':28, 'name':"Static Disk Potential",
             'params':['DISK_POTENTIAL','DISK_MASS_M0','DISK_SCALE_R0']},
            {'id':29, 'name':"Static NFW Potential",
             'params':['STATICNFW','NFW_C','NFW_M200','NFW_E','NFW_DARKFRACTION']},
            {'id':30, 'name':"Static Isothermal Sphere Potential",
             'params':['STATICISO','ISO_M200','ISO_R200','ISO_E','ISO_FRACTION']},
            {'id':31, 'name':"Static Hernquist Potential",
             'params':['STATICHQ','HQ_M200','HQ_C','HQ_DARKFRACTION']},
            {'id':32, 'name':"Growing Disk Potential",
             'params':['GROWING_DISK_POTENTIAL']},
            {'id':33, 'name':"Dark energy",
             'params':['DARKENERGY','TIMEDEPDE','RESCALEVINI','EXTERNALHUBBLE','TIMEDEPGRAV','DARKENERGY_DEBUG']},
            {'id':34, 'name':"Glass making/ 2nd-order initial conditions / Initial conditions options",
             'params':['SECOND_ORDER_ICS','LONGIDS','OFFSET_FOR_NON_CONTIGUOUS_IDS','GENERATE_GAS_IN_ICS','SPLIT_PARTICLE_TYPE',
                       'NTYPES_ICS']},
            {'id':35, 'name':"Simple turbulence test",
             'params':['VS_TURB','POWERSPEC_GRID','AB_TURB','READ_LEGACY_ICS']},
            {'id':36, 'name':"Degenerate Equation of State",
             'params':['EOS_DEGENERATE','EOS_COULOMB_CORRECTIONS','EOS_NSPECIES','RELAXOBJECT','RELAXOBJECT_COOLING',
                       'RELAXOBJECT_BINARY','PASSIVE_SCALARS']},
            {'id':37, 'name':"Nuclear Network",
             'params':['NUCLEAR_NETWORK','NETWORK_NSE','NETWORK_PARDISO','NETWORK_SCREENING','REACLIB1',
                       'NUCLEAR_NETWORK_DETONATE']},
            {'id':38, 'name':"OPAL Equation of State",
             'params':['EOS_OPAL','EOS_NSPECIES']},
            {'id':39, 'name':"Radiative transfer options",
             'params':['RT_ENABLE','RT_COOLING_PHOTOHEATING','RT_ADVECT','RT_CGMETHOD','RT_SLOWLIGHT','RT_N_DIR',
                       'RT_COMBINE_N_DIR_IN_OUTPUT','RT_ALLOW_ABSORBING_CELLS','RT_SPREAD_SOURCE','RT_STELLAR_SOURCES',
                       'RT_HEALPIX_NSIDE','RT_INCLUDE_HE','SOURCE_PERIODIC','DO_NOT_MOVE_GAS','HYDROGEN_ONLY']},
            {'id':40, 'name':"Calculate Hessian Matrix",
             'params':['SECOND_DERIVATIVES','SLOPE_LIMIT_HESSIANS','RECONSTRUCT_GRADIENTS']},
            {'id':41, 'name':"Navier-Stokes Terms",
             'params':['GLOBAL_VISCOSITY','USE_KINEMATIC_VISCOSITY','ALPHA_VISCOSITY','LOCAL_VISCOSITY','THERMAL_CONDUCTION',
                       'TRACER_DIFFUSION']},
            {'id':42, 'name':"Circumstellar Disks",
             'params':['CIRCUMSTELLAR','CIRCUMSTELLAR_WBOUNDARIES','CIRCUMSTELLAR_IRRADIATION','CIRCUMSTELLAR_SINKS',
                       'CIRCUMSTELLAR_PLANET_GROWTH','GRAVITY_FROM_STARS_PLANETS_ONLY','CENTRAL_MASS_POTENTIAL',
                       'BINARY_POTENTIAL','LOCALLY_ISOTHERM_DISK']},
            {'id':43, 'name':"Special Boundaries within domain",
             'params':['SPECIAL_BOUNDARY','COAXIAL_BOUNDARIES']},
            {'id':44, 'name':"Windtunnel",
             'params':['WINDTUNNEL','WINDTUNNEL_COORD','WINDTUNNEL_EXTERNAL_SOURCE']},
            {'id':45, 'name':"Boundaries with optional inflow/outflow",
             'params':['BOUNDARY_INFLOWOUTFLOW_MINID','BOUNDARY_INFLOWOUTFLOW_MAXID','BOUNDARY_REFL_FLUIDSIDE_MINID',
                       'BOUNDARY_REFL_FLUIDSIDE_MAXID','BOUNDARY_REFL_SOLIDSIDE_MINID','BOUNDARY_REFL_SOLIDSIDE_MAXID',
                       'BOUNDARY_REFL_ACTS_AS_SOURCE','BOUNDARY_STICKY_MINID','BOUNDARY_STICKY_MAXID']},
            {'id':46, 'name':"GFM - Galaxy Formation Module",
             'params':['GFM','GFM_STELLAR_EVOLUTION','GFM_CONST_IMF','GFM_VARIABLE_IMF','GFM_PREENRICH','GFM_EXACT_NUMNGB',
                       'GFM_WINDS','GFM_WINDS_VARIABLE','GFM_WINDS_VARIABLE_HUBBLE','GFM_WINDS_HUBBLESCALING',
                       'GFM_WINDS_MASSSCALING','GFM_WIND_ENERGY_METAL_DEPENDENCE','GFM_WIND_ENERGY_METAL_DEPENDENCE_TANH',
                       'GFM_WINDS_STRIPPING','GFM_WINDS_THERMAL','GFM_WINDS_THERMAL_NEWDEF','GFM_BIPOLAR_WINDS','GFM_WINDS_LOCAL',
                       'GFM_STELLAR_FEEDBACK','GFM_PRIMORDIAL_RATES','GFM_COOLING_METAL','GFM_UVB_CORRECTIONS',
                       'GFM_AGN_RADIATION','GFM_STELLAR_PHOTOMETRICS','GFM_OUTPUT_MASK','GFM_DUST','GFM_DUST_DESTMODE',
                       'GFM_DUST_SPUTTERING','GFM_CHECKS','GFM_DISCARD_ENRICHMENT_GRADIENTS','GFM_NORMALIZED_METAL_ADVECTION',
                       'GFM_OUTPUT_BIRTH_POS','GFM_CHEMTAGS','GFM_WINDS_SAVE_PARTTYPE','GFM_DISCRETE_ENRICHMENT','GFM_SPLITFE',
                       'GFM_RPROCESS']},
            {'id':47, 'name':"Modified Gas Cooling",
             'params':['RADCOOL','RADCOOL_HOTHALO','RADCOOL_HOTHALO_METAL_BOOST']},
            {'id':48, 'name':"FM - Star formation and feedback module",
             'params':['FM_SFR','FM_STAR_FEEDBACK','FM_STAR_FEEDBACK_KICK_TYPE','NON_STOCHASTIC_MOMENTUM_FEEDBACK',
                       'INJECT_INTO_SINGLE_CELL','DIRECT_MOMENTUM_INJECTION_FEEDBACK','OUTPUT_SF_PROBABILITY','TEST_SFR',
                       'USE_POLYTROPIC_EQSTATE','DELAYED_COOLING','SHUTOFFTIME_UPDATE','DELAYED_COOLING_TURB',
                       'INSTANTANEOUS_DEPOSITION','EXPLICIT_COOLING','COMPUTE_SFR_FROM_H2','TEST_COOLING_METAL',
                       'OUTPUT_STELLAR_FEEDBACK','OUTPUT_MOLECULAR_FRACTION','OUTPUT_OPTICAL_DEPTH','RADPRESS_OPT_THIN',
                       'RADPRESS_OPT_THIN_LUMPERMASS','RADPRESS_OPT_THICK','FM_RADIATION_FEEDBACK','FM_RADIATION_FEEDBACK_DEBUG',
                       'FM_EARLY_STAR_FEEDBACK','FM_EARLY_STAR_FEEDBACK_KICK_TYPE','OUTPUT_EARLY_STELLAR_FEEDBACK',
                       'FM_MASS_WEIGHT_SN','FM_VAR_SN_EFF']},
            {'id':49, 'name':"Conduction",
             'params':['MONOTONE_CONDUCTION','CONDUCTION_ISOTROPIC','CONDUCTION_ANISOTROPIC','CONDUCTION_CONSTANT',
                       'CONDUCTION_SATURATION','IMPLICIT_TI','SEMI_IMPLICIT_TI','RESTRICT_KAPPA','MULTIPLE_TIMESTEP',
                       'NON_LINEAR_SLOPE_LIMITERS']},
            {'id':50, 'name':"OTVET IMPLEMENTATION",
             'params':['OTVET','OTVET_CHEMISTRY_PS2009','OTVET_CHEMISTRY_PS2011','OTVET_NOGRAVITY','OTVET_NOTMOVEGAS',
                       'OTVET_OUTPUT_ET','EDDINGTON_TENSOR_STARS','OTVET_MODIFY_EDDINGTON_TENSOR','OTVET_FLUXLIMITER',
                       'OTVET_CHANGEFLUXLIMITER','OTVET_FIXTIMESTEP','OTVET_COOLING_HEATING','OTVET_MULTI_FREQUENCY',
                       'OTVET_INCLUDE_HE','OTVET_SCATTER_SOURCE','OTVET_OUTPUT_SOURCEHSML','OTVET_CHECK_PHOTONCOUNT',
                       'OTVET_NOCOLLISION_IONIZATION','OTVET_SILENT','OTVET_MODIFY_EDDINGTON_TENSOR']},
            {'id':51, 'name':"TG's switches for primordial simulations",
             'params':['TGSET','TGCHEM','HEALRAY','SINKS']},
            {'id':52, 'name':"SIDM - Self-Interacting DM",
             'params':['SIDM','SIDM_CONST_CROSS','SIDM_STATES','SIDM_REACTIONS','SIDM_READ_ICS','SIDM_NO_SCATTER',
                       'SIDM_NO_TIMESTEP','SIDM_NO_KINEMATICS','SIDM_NO_NGB_SEL','SIDM_NO_MASSCHANGE']},
            {'id':53, 'name':"ISM - new detailed ISM/stellar feedback model ",
             'params':['ISM','ISM_LOCAL_RADIATION_PRESSURE','ISM_LONG_RANGE_RADIATION_PRESSURE','ISM_HII_PHOTO_HEATING',
                       'ISM_H2_SFR','ISM_OUTPUT_FIELDS']},
            {'id':54, 'name':"On-the-fly shock finder",
             'params':['SHOCK_FINDER_BEFORE_OUTPUT','SHOCK_FINDER_ON_THE_FLY']},
            {'id':55, 'name':"Post-processing shock finder, please read the instructions in shock_finder.h",
             'params':['SHOCK_FINDER_POST_PROCESSING','SHOCK_FINDER_AREPO','UNLIMITED_GRADIENTS','ZONE_JUMP_P','ZONE_JUMP_T',
                       'SHOCK_DIR_GRAD_T','SHOCK_JUMP_T','SURFACE_SPHERE_APPROX','SURFACE_ANGLE_APPROX','RESET_WRONG_JUMPS',
                       'RESET_WRONG_RHO_JUMPS','RESET_WRONG_P_JUMPS','OUTPUT_GRAVITY_FRACTION','SKIP_BORDER']},
            {'id':56, 'name':"atomic dark matter (in fluid approximation)",
             'params':['ATOMIC_DM']},
            {'id':57, 'name':"Binary stellar systems",
             'params':['STAR_INDEX','BINARYLOG','SPECIAL_SOFTENINGS','REDUCE_SOFTENINGS','ID_RGCORE','DMLOWESTTIMEBIN','DMFIXED']},
            {'id':58, 'name':"FLD",
             'params':['FLD','FLD_CONES','FLD_NCONES','FLD_CONST_KAPPA','FLD_MARSHAK','FLD_HYPRE','FLD_HYPRE_IJ1',
                       'FLD_HYPRE_IJ2','HYPRE_PCG','FLD_MG','FLD_MG_GS','FLD_ANISOTROPIC_CIRCULAR','FLD_NO_TEMP_UPDATE',
                       'FLD_SILENT','FLD_TEST_BOUNDARY','FLD_UPPER_BOUNDARY_MINID','FLD_UPPER_BOUNDARY_MAXID',
                       'FLD_LOWER_BOUNDARY_MINID','FLD_LOWER_BOUNDARY_MAXID']},
            {'id':59, 'name':"Discontinuous Galerkin (DG)",
             'params':['DG','DG_SET_IC_FROM_AVERAGES','DG_TEST_PROBLEM','DG_VERBOSE','DG_DEBUG','DEGREE_K','CALC_QUADRATURE_DATA',
                       'RIEMANN_HLLC','MINMOD_B','DISCONTINUITY_DETECTION','OUTPUT_DG_DISCONTINUITIES',
                       'OUTPUT_DG_INFLOW_BOUNDARIES','ANGLE_BOUND','CHARACTERISTIC_LIMITER','CONSERVED_LIMITER',
                       'POSITIVITY_LIMITER','FIX_MEAN_VALUES']},
            {'id':60, 'name':"Deprecated",
             'params':['CONDUCTION']},
            {'id':61, 'name':"Sink Particles",
             'params':['GRACKLE','GRACKLE_H2','GRACKLE_D','GRACKLE_TAB','GRACKLE_ABUNDANCE_IN_ICS','GRACKLE_VERBOSE',
                       'SINK_PARTICLES','DUMP_SINK_PARTICLE_INFO','SINK_PARTICLES_SKIM_CELL_MASS',
                       'SINK_PARTICLES_VARIABLE_ACC_RADIUS','SINK_PARTICLES_FEEDBACK']},
            {'id':62, 'name':"SG chemistry options",
             'params':['SGCHEM','SGCHEM_NO_HIGHN_DCHEM','SGCHEM_NO_MOLECULES','CHEMISTRYNETWORK','JEANS_REFINEMENT',
                       'NO_TARGET_MASS_CONDITION','STATIC_CHEMISTRY_TEST','ADVECTION_ONLY','CHEM_IMAGE','ABHE','SG_HEADER_FLAG',
                       'DEBUG_EVOLVE','DEBUG_RATE_EQ','SGCHEM_ACCRETION_LUMINOSITY','SGCHEM_CONSTANT_ALPHAB',
                       'SGCHEM_DISABLE_COMPTON_COOLING','DEBUG_PARTICLE_ID','SGCHEM_TEMPERATURE_FLOOR']},
            {'id':63, 'name':"TreeCol",
             'params':['TREE_RAD','TREE_RAD_H2','TREE_RAD_CO','NSIDE','OUTPUTCOL','TREE_RAD_VEL']},
            {'id':64, 'name':"SimpleX - radiative transfer of ionizing radiation on the Delaunay triangulation",
             'params':['SGCHEM_RT','SINK_SIMPLEX','SIMPLEX','SX_CHEMISTRY','SX_NDIR','SX_SOURCES','SX_NUM_ROT','SX_HYDROGEN_ONLY',
                       'SX_DISPLAY_STATS','SX_DISPLAY_TIMERS','SX_DISPLAY_TIMERS_SITE','SX_DISPLAY_MEMORY','SX_OUTPUT_IMAGE',
                       'SX_OUTPUT_IMAGE_ALL','SX_OUTPUT_FLUX','SX_RECOMBINE','SX_RADIATION_PRESSURE','SX_FLOAT_PRECISION',
                       'SX_PP_ZERO_SNAPSHOT','SX_SKIP_RADIUS']},
            {'id':65, 'name':"Healthtest of the machine partition at startup",
             'params':['MAX_VARIATION_TOLERANCE']},
            {'id':66, 'name':"Other", 'params':[]},
        ]
        self.params = {
            'NTYPES': {'value':False,'dtype':'i','default':6,'format':'%d'},
            'PERIODIC': {'value':False,'dtype':'e'},
            'TWODIMS': {'value':False,'dtype':'e'},
            'AXISYMMETRY': {'value':False,'dtype':'e'},
            'ONEDIMS': {'value':False,'dtype':'e'},
            'LONG_X': {'value':False,'dtype':'f','default':10.0,'format':'%f'},
            'LONG_Y': {'value':False,'dtype':'f','default':2.0,'format':'%f'},
            'LONG_Z': {'value':False,'dtype':'f','default':10.0,'format':'%f'},
            'REFLECTIVE_X': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'REFLECTIVE_Y': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'REFLECTIVE_Z': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'MHD': {'value':False,'dtype':'e'},
            'MHD_DONT_PRINT_BMAGSUM': {'value':False,'dtype':'e'},
            'MHD_CT': {'value':False,'dtype':'e'},
            'MHD_CT_IC': {'value':False,'dtype':'e'},
            'MHD_CT_PERTURB_POSITIONS': {'value':False,'dtype':'e'},
            'MHD_DIVBCLEANING': {'value':False,'dtype':'e'},
            'MHD_POWELL': {'value':False,'dtype':'e'},
            'MHD_POWELL_LIMIT_TIMESTEP': {'value':False,'dtype':'e'},
            'MHD_SEEDFIELD': {'value':False,'dtype':'e'},
            'MHD_SEEDPSPEC': {'value':False,'dtype':'e'},
            'MHD_THERMAL_ENERGY_SWITCH': {'value':False,'dtype':'e'},
            'COOLING': {'value':False,'dtype':'e'},
            'UVB_SELF_SHIELDING': {'value':False,'dtype':'e'},
            'USE_SFR': {'value':False,'dtype':'e'},
            'QUICK_LYALPHA': {'value':False,'dtype':'e'},
            'QUICK_LYALPHA_LATETIMEONLY': {'value':False,'dtype':'e'},
            'SFR_KEEP_CELLS': {'value':False,'dtype':'e'},
            'GAMMA': {'value':False,'dtype':'f','default':1.4,'format':'%f'},
            'ISOTHERM_EQS': {'value':False,'dtype':'e'},
            'USE_ENTROPY_FOR_COLD_FLOWS': {'value':False,'dtype':'e'},
            'ENTROPY_MACH_THRESHOLD': {'value':False,'dtype':'f','default':1.1,'format':'%f'},
            'PREHEATING': {'value':False,'dtype':'e'},
            'NOHYDRO': {'value':False,'dtype':'e'},
            'SPECIAL_RELATIVITY': {'value':False,'dtype':'e'},
            'SPECIAL_RELATIVITY_HLLC': {'value':False,'dtype':'e'},
            'SR_HLLC_ZERO_COMPVEL': {'value':False,'dtype':'e'},
            'GENERAL_RELATIVITY': {'value':False,'dtype':'e'},
            'METRIC_TYPE': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'ATMOSPHERE_GENERAL_RELATIVITY': {'value':False,'dtype':'e'},
            'ADIABATIC_GENERAL_RELATIVITY': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'NON_IDEAL_MHD': {'value':False,'dtype':'e'},
            'OHMIC_DIFFUSION': {'value':False,'dtype':'e'},
            'IMPLICIT_OHMIC_DIFFUSION': {'value':False,'dtype':'e'},
            'ONLY_OHMIC_DIFFUSION': {'value':False,'dtype':'e'},
            'DIFFUSION': {'value':False,'dtype':'e'},
            'COSMIC_RAYS': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_COOLING': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_ALFVEN_COOLING': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_STREAMING': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_STREAMING_ANISOTROPIC': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_CONSTANT_TIMESTEP': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_GLOBAL_TIMESTEP': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_EXPLICIT': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_FULL_NORMAL_GRADIENT': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_ALWAYS_USE_PRECONDITIONER': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_ANISOTROPIC': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_LIMITER': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_DIFFUSION_OLD': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_SN_INJECTION': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_SHOCK_ACCELERATION': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_IN_ICS': {'value':False,'dtype':'e'},
            'COSMIC_RAYS_MAGNETIC_OBLIQUITY': {'value':False,'dtype':'e'},
            'OUTPUT_CR_PRESSURE_GRADIENT': {'value':False,'dtype':'e'},
            'NUM_THREADS': {'value':False,'dtype':'i','default':4,'format':'%d'},
            'IMPOSE_PINNING': {'value':False,'dtype':'e'},
            'IMPOSE_PINNING_OVERRIDE_MODE': {'value':False,'dtype':'e'},
            'GENERIC_ASYNC': {'value':False,'dtype':'e'},
            'AMR': {'value':False,'dtype':'e'},
            'VORONOI': {'value':False,'dtype':'e'},
            'VARIABLE_GAMMA': {'value':False,'dtype':'e'},
            'RIEMANN_HLL': {'value':False,'dtype':'e'},
            'RIEMANN_HLLC': {'value':False,'dtype':'e'},
            'RIEMANN_ROSUNOV': {'value':False,'dtype':'e'},
            'RIEMANN_HLLD': {'value':False,'dtype':'e'},
            'RIEMANN_GAMMA': {'value':False,'dtype':'e'},
            'AMR_CONNECTIONS': {'value':False,'dtype':'e'},
            'AMR_GRADIENTS': {'value':False,'dtype':'e'},
            'AMR_REDUCE_DOMAIN_DECOMPOISTION': {'value':False,'dtype':'e'},
            'TVD_SLOPE_LIMITER': {'value':False,'dtype':'e'},
            'TVD_SLOPE_LIMITER_VANLEER': {'value':False,'dtype':'e'},
            'TVD_SLOPE_LIMITER_SUPERBEE': {'value':False,'dtype':'e'},
            'TVD_SLOPE_LIMITER_ALBADA': {'value':False,'dtype':'e'},
            'TVD_SLOPE_LIMITER_MINBEE': {'value':False,'dtype':'e'},
            'GRADIENT_LIMITER_DUFFELL': {'value':False,'dtype':'e'},
            'DISABLE_TIME_EXTRAPOLATION': {'value':False,'dtype':'e'},
            'DISABLE_SPATIAL_EXTRAPOLATION': {'value':False,'dtype':'e'},
            'NO_SCALAR_GRADIENTS': {'value':False,'dtype':'e'},
            'GRADIENTS_GREEN_GAUSS': {'value':False,'dtype':'e'},
            'VORONOI_STATIC_MESH': {'value':False,'dtype':'e'},
            'VORONOI_STATIC_MESH_DO_DOMAIN_DECOMPOSITION': {'value':False,'dtype':'e'},
            'REGULARIZE_MESH_CM_DRIFT': {'value':False,'dtype':'e'},
            'REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED': {'value':False,'dtype':'e'},
            'REGULARIZE_MESH_FACE_ANGLE': {'value':False,'dtype':'e'},
            'REGULARIZE_MESH_OPTIMAL': {'value':False,'dtype':'e'},
            'OUTPUT_MESH_FACE_ANGLE': {'value':False,'dtype':'e'},
            'CALCULATE_VERTEX_VELOCITY_DIVERGENCE': {'value':False,'dtype':'e'},
            'STICKY_POINTS_ON_REFLECTIVE_SURFACE': {'value':False,'dtype':'e'},
            'FORCE_EQUAL_TIMESTEPS': {'value':False,'dtype':'e'},
            'TREE_BASED_TIMESTEPS': {'value':False,'dtype':'e'},
            'DECOUPLE_TIMESTEPS': {'value':False,'dtype':'e'},
            'MUSCL_HANCOCK': {'value':False,'dtype':'e'},
            'RUNGE_KUTTA_FULL_UPDATE': {'value':False,'dtype':'e'},
            'DVR_RENDER': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'DVR_RENDER_SMOOTH': {'value':False,'dtype':'e'},
            'DVR_RENDER_ORTHOGONAL': {'value':False,'dtype':'e'},
            'DVR_NUM_FIELDS': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'DVR_STAY_IN_BOX': {'value':False,'dtype':'e'},
            'VORONOI_MESHOUTPUT': {'value':False,'dtype':'e'},
            'VORONOI_IMAGES_FOREACHSNAPSHOT': {'value':False,'dtype':'e'},
            'VORONOI_FREQUENT_IMAGES': {'value':False,'dtype':'e'},
            'VORONOI_FIELD_DUMP_PIXELS_X': {'value':False,'dtype':'i','default':1536,'format':'%d'},
            'VORONOI_FIELD_DUMP_PIXELS_Y': {'value':False,'dtype':'i','default':150,'format':'%d'},
            'VORONOI_VELOCITY_FIELD_2D': {'value':False,'dtype':'e'},
            'VORONOI_FIELD_COMPENSATE_VX': {'value':False,'dtype':'f','default':4.0,'format':'%f'},
            'VORONOI_FIELD_COMPENSATE_VY': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'VORONOI_NEW_IMAGE': {'value':False,'dtype':'e'},
            'VORONOI_PROJ_TEMP': {'value':False,'dtype':'e'},
            'VORONOI_PROJ': {'value':False,'dtype':'e'},
            'VORONOI_MULTIPLE_PROJECTIONS': {'value':False,'dtype':'e'},
            'VORONOI_NOGRADS': {'value':False,'dtype':'e'},
            'REFINEMENT_SPLIT_CELLS': {'value':False,'dtype':'e'},
            'REFINEMENT_MERGE_CELLS': {'value':False,'dtype':'e'},
            'REFINEMENT_MERGE_PAIRS': {'value':False,'dtype':'e'},
            'REFINEMENT_VOLUME_LIMIT': {'value':False,'dtype':'e'},
            'REFINEMENT_HIGH_RES_GAS': {'value':False,'dtype':'e'},
            'REFINEMENT_AROUND_BH': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'DEREFINE_ONLY_DENSE_GAS': {'value':False,'dtype':'e'},
            'NODEREFINE_BACKGROUND_GRID': {'value':False,'dtype':'e'},
            'DEREFINE_GENTLY': {'value':False,'dtype':'e'},
            'OPTIMIZE_MESH_MEMORY_FOR_REFINEMENT': {'value':False,'dtype':'e'},
            'REFINEMENT_AROUND_DM': {'value':False,'dtype':'e'},
            'MESHRELAX': {'value':False,'dtype':'e'},
            'MESHRELAX_DENSITY_IN_INPUT': {'value':False,'dtype':'e'},
            'ADDBACKGROUNDGRID': {'value':False,'dtype':'i','default':16,'format':'%d'},
            'AMR_REMAP': {'value':False,'dtype':'e'},
            'SELFGRAVITY': {'value':False,'dtype':'e'},
            'VALPOTENTIAL': {'value':False,'dtype':'e'},
            'HIERARCHICAL_GRAVITY': {'value':False,'dtype':'e'},
            'CELL_CENTER_GRAVITY': {'value':False,'dtype':'e'},
            'NO_GAS_SELFGRAVITY': {'value':False,'dtype':'e'},
            'GRAVITY_NOT_PERIODIC': {'value':False,'dtype':'e'},
            'GRAVITY_TALLBOX': {'value':False,'dtype':'e'},
            'NO_SELFGRAVITY_TYPE': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'ALLOW_DIRECT_SUMMATION': {'value':False,'dtype':'e'},
            'DIRECT_SUMMATION_THRESHOLD': {'value':False,'dtype':'i','default':1000,'format':'%d'},
            'EXACT_GRAVITY_FOR_PARTICLE_TYPE': {'value':False,'dtype':'i','default':4,'format':'%d'},
            'EXTERNALGRAVITY': {'value':False,'dtype':'e'},
            'EXTERNALGY': {'value':False,'dtype':'f','default':0.0,'format':'%f'},
            'EXTERNALDISKPOTENTIAL': {'value':False,'dtype':'e'},
            'EXTERNALSHEARBOX': {'value':False,'dtype':'e'},
            'EXTERNALSHEARBOX_KSRATE_RANDOM': {'value':False,'dtype':'e'},
            'EXTERNALSHEARBOX_KSRATE_UPDATE_PARAM': {'value':False,'dtype':'e'},
            'ENFORCE_JEANS_STABILITY_OF_CELLS_EEOS': {'value':False,'dtype':'e'},
            'ENFORCE_JEANS_STABILITY_OF_CELLS': {'value':False,'dtype':'e'},
            'EVALPOTENTIAL': {'value':False,'dtype':'e'},
            'EXTERNALSHEETY': {'value':False,'dtype':'e'},
            'COMPUTE_POTENTIAL_ENERGY': {'value':False,'dtype':'e'},
            'RANDOMIZE_DOMAINCENTER': {'value':False,'dtype':'e'},
            'DO_NOT_RANDOMIZE_DOMAINCENTER': {'value':False,'dtype':'e'},
            'NSOFTTYPES': {'value':False,'dtype':'i','default':4,'format':'%d'},
            'MULTIPLE_NODE_SOFTENING': {'value':False,'dtype':'e'},
            'INDIVIDUAL_GRAVITY_SOFTENING': {'value':False,'dtype':'s','default':'2+4','format':'%s'},
            'ADAPTIVE_HYDRO_SOFTENING': {'value':False,'dtype':'e'},
            'NSOFTTYPES_HYDRO': {'value':False,'dtype':'i','default':120,'format':'%d'},
            'PMGRID': {'value':False,'dtype':'i','default':512,'format':'%d'},
            'ASMTH': {'value':False,'dtype':'f','default':1.25,'format':'%f'},
            'RCUT': {'value':False,'dtype':'f','default':6.0,'format':'%f'},
            'PLACEHIGHRESREGION': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'ENLARGEREGION': {'value':False,'dtype':'f','default':1.1,'format':'%f'},
            'GRIDBOOST': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'ONLY_PM': {'value':False,'dtype':'e'},
            'FFT_COLUMN_BASED': {'value':False,'dtype':'e'},
            'PM_ZOOM_OPTIMIZED': {'value':False,'dtype':'e'},
            'AUTO_SWAP_ENDIAN_READIC': {'value':False,'dtype':'e'},
            'CHUNKING': {'value':False,'dtype':'e'},
            'DOUBLEPRECISION': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'DOUBLEPRECISION_FFTW': {'value':False,'dtype':'e'},
            'OUTPUT_IN_DOUBLEPRECISION': {'value':False,'dtype':'e'},
            'INPUT_IN_DOUBLEPRECISION': {'value':False,'dtype':'e'},
            'OUTPUT_COORDINATES_IN_DOUBLEPRECISION': {'value':False,'dtype':'e'},
            'NGB_TREE_DOUBLEPRECISION': {'value':False,'dtype':'e'},
            'FOF': {'value':False,'dtype':'e'},
            'FOF_PRIMARY_LINK_TYPES': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'FOF_SECONDARY_LINK_TYPES': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'FOF_SECONDARY_LINK_TARGET_TYPES': {'value':False,'dtype':'e'},
            'FOF_GROUP_MIN_LEN': {'value':False,'dtype':'i','default':32,'format':'%d'},
            'FOF_LINKLENGTH': {'value':False,'dtype':'f','default':0.16,'format':'%f'},
            'FOF_FUZZ_SORT_BY_NEAREST_GROUP': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'FOF_STOREIDS': {'value':False,'dtype':'e'},
            'USE_AREPO_FOF_WITH_GADGET_FIX': {'value':False,'dtype':'e'},
            'ADD_GROUP_PROPERTIES': {'value':False,'dtype':'e'},
            'SUBFIND': {'value':False,'dtype':'e'},
            'SAVE_HSML_IN_SNAPSHOT': {'value':False,'dtype':'e'},
            'SUBFIND_MEASURE_H2MASS': {'value':False,'dtype':'e'},
            'SUBFIND_CALC_MORE': {'value':False,'dtype':'e'},
            'SUBFIND_EXTENDED_PROPERTIES': {'value':False,'dtype':'e'},
            'METALS': {'value':False,'dtype':'e'},
            'MIN_METALLICITY_ON_STARTUP': {'value':False,'dtype':'e'},
            'STELLARAGE': {'value':False,'dtype':'e'},
            'SOFTEREQS': {'value':False,'dtype':'e'},
            'MODIFIED_EOS': {'value':False,'dtype':'e'},
            'SLOW_RELAX_TO_EOS': {'value':False,'dtype':'e'},
            'BLACK_HOLES': {'value':False,'dtype':'e'},
            'BH_THERMALFEEDBACK': {'value':False,'dtype':'e'},
            'BH_THERMALFEEDBACK_ACC': {'value':False,'dtype':'e'},
            'BH_NF_RADIO': {'value':False,'dtype':'e'},
            'DRAINGAS': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'BH_EXACT_INTEGRATION': {'value':False,'dtype':'e'},
            'BH_BONDI_DEFAULT': {'value':False,'dtype':'e'},
            'BH_BONDI_DENSITY': {'value':False,'dtype':'e'},
            'BH_BONDI_CAPTURE': {'value':False,'dtype':'e'},
            'BH_BONDI_DISK_VORTICITY': {'value':False,'dtype':'e'},
            'BH_DO_NOT_PREVENT_MERGERS': {'value':False,'dtype':'e'},
            'BH_USE_GASVEL_IN_BONDI': {'value':False,'dtype':'e'},
            'BH_USE_ALFVEN_SPEED_IN_BONDI': {'value':False,'dtype':'e'},
            'MASSIVE_SEEDS': {'value':False,'dtype':'e'},
            'MASSIVE_SEEDS_MERGER': {'value':False,'dtype':'e'},
            'BH_NEW_CENTERING': {'value':False,'dtype':'e'},
            'BH_FRICTION': {'value':False,'dtype':'e'},
            'BH_FRICTION_AGGRESSIVE': {'value':False,'dtype':'e'},
            'BH_HARMONIC_OSCILLATOR_FORCE': {'value':False,'dtype':'e'},
            'BH_DRAG': {'value':False,'dtype':'e'},
            'REPOSITION_ON_POTMIN': {'value':False,'dtype':'e'},
            'BH_PRESSURE_CRITERION': {'value':False,'dtype':'e'},
            'BH_RELATIVE_NGB_DEVIATION': {'value':False,'dtype':'e'},
            'OUTPUT_BLACK_HOLE_TIMESTEP': {'value':False,'dtype':'e'},
            'UNIFIED_FEEDBACK': {'value':False,'dtype':'e'},
            'BH_BUBBLES': {'value':False,'dtype':'e'},
            'BH_MAGNETIC_BUBBLES': {'value':False,'dtype':'e'},
            'BH_MAGNETIC_DIPOLAR_BUBBLES': {'value':False,'dtype':'e'},
            'BH_ADIOS_WIND': {'value':False,'dtype':'e'},
            'BH_ADIOS_DENS_DEP_EFFICIANCY': {'value':False,'dtype':'e'},
            'BH_ADIOS_WIND_WITH_QUASARTHRESHOLD': {'value':False,'dtype':'e'},
            'BH_ADIOS_WIND_WITH_VARIABLE_QUASARTHRESHOLD': {'value':False,'dtype':'e'},
            'BH_ADIOS_WIND_DIRECTIONAL': {'value':False,'dtype':'e'},
            'BH_ADIOS_RANDOMIZED': {'value':False,'dtype':'e'},
            'BH_ADIOS_ONLY_ABOVE_MINIMUM_DENSITY': {'value':False,'dtype':'e'},
            'BH_CONTINOUS_MODE_SWITCH': {'value':False,'dtype':'e'},
            'REFINEMENT_AROUND_BH_FIXED': {'value':False,'dtype':'e'},
            'SUPPRESS_SF_IN_REFINEMENT_REGION': {'value':False,'dtype':'e'},
            'BH_BIPOLAR_FEEDBACK': {'value':False,'dtype':'e'},
            'TRACER_FIELD': {'value':False,'dtype':'e'},
            'TRACER_PARTICLE': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'TRACER_MC': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'TRACER_MC_CHECKS': {'value':False,'dtype':'e'},
            'GENERATE_TRACER_PARTICLE_IN_ICS': {'value':False,'dtype':'e'},
            'GENERATE_TRACER_MC_IN_ICS': {'value':False,'dtype':'e'},
            'TRACER_PART_NUM_FLUID_QUANTITIES': {'value':False,'dtype':'i','default':8,'format':'%d'},
            'TRACER_PART_STORE_WHAT': {'value':False,'dtype':'s','default':'1+2+4+8+16+32+64+128','format':'%s'},
            'TRACER_MC_NUM_FLUID_QUANTITIES': {'value':False,'dtype':'i','default':13,'format':'%d'},
            'TRACER_MC_STORE_WHAT': {'value':False,'dtype':'s','default':'1+2+4+8+16+32+64+128+256+512+1024+2048+4096+8192','format':'%s'},
            'TRACER_NO_RESET_EACH_SNAP': {'value':False,'dtype':'e'},
            'TRACER_MC_SKIPLOAD': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'FOF_DISABLE_SNAP_REWRITE': {'value':False,'dtype':'e'},
            'TRACER_TRAJECTORY': {'value':False,'dtype':'e'},
            'TRACER_TRAJECTORY_GENERATE': {'value':False,'dtype':'e'},
            'READ_DM_AS_GAS': {'value':False,'dtype':'e'},
            'NO_ID_UNIQUE_CHECK': {'value':False,'dtype':'e'},
            'RUNNING_SAFETY_FILE': {'value':False,'dtype':'e'},
            'LOAD_TYPES': {'value':False,'dtype':'s','default':'1+2+4+16+32','format':'%s'},
            'READ_COORDINATES_IN_DOUBLE': {'value':False,'dtype':'e'},
            'IDS_OFFSET': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'TILE_ICS': {'value':False,'dtype':'e'},
            'COMBINETYPES': {'value':False,'dtype':'e'},
            'MULTIPLE_RESTARTS': {'value':False,'dtype':'e'},
            'TOLERATE_WRITE_ERROR': {'value':False,'dtype':'e'},
            'OPTIMIZE_MEMORY_USAGE': {'value':False,'dtype':'e'},
            'SUBBOX_SNAPSHOTS': {'value':False,'dtype':'e'},
            'PROCESS_TIMES_OF_OUTPUTLIST': {'value':False,'dtype':'e'},
            'EXTENDED_GHOST_SEARCH': {'value':False,'dtype':'e'},
            'DOUBLE_STENCIL': {'value':False,'dtype':'e'},
            'TETRA_INDEX_IN_FACE': {'value':False,'dtype':'e'},
            'VORONOI_DYNAMIC_UPDATE': {'value':False,'dtype':'e'},
            'COFFEE_PROBLEM': {'value':False,'dtype':'e'},
            'NOH_PROBLEM': {'value':False,'dtype':'e'},
            'SHIFT_BY_HALF_BOX': {'value':False,'dtype':'e'},
            'DISABLE_VELOCITY_CSND_SLOPE_LIMITING': {'value':False,'dtype':'e'},
            'NO_MPI_IN_PLACE': {'value':False,'dtype':'e'},
            'NO_ISEND_IRECV_IN_DOMAIN': {'value':False,'dtype':'e'},
            'FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG': {'value':False,'dtype':'e'},
            'USE_MPIALLTOALLV_IN_DOMAINDECOMP': {'value':False,'dtype':'e'},
            'MPI_HYPERCUBE_ALLGATHERV': {'value':False,'dtype':'e'},
            'MPISENDRECV_CHECKSUM': {'value':False,'dtype':'e'},
            'NOTREERND': {'value':False,'dtype':'e'},
            'ENLARGE_DYNAMIC_RANGE_IN_TIME': {'value':False,'dtype':'e'},
            'NOSTOP_WHEN_BELOW_MINTIMESTEP': {'value':False,'dtype':'e'},
            'DO_NOT_CREATE_STAR_PARTICLES': {'value':False,'dtype':'e'},
            'DMPIC': {'value':False,'dtype':'e'},
            'ALLOWEXTRAPARAMS': {'value':False,'dtype':'e'},
            'RADIATIVE_RATES': {'value':False,'dtype':'e'},
            'FIX_SPH_PARTICLES_AT_IDENTICAL_COORDINATES': {'value':False,'dtype':'e'},
            'VEL_POWERSPEC': {'value':False,'dtype':'e'},
            'ADJ_BOX_POWERSPEC': {'value':False,'dtype':'e'},
            'DISABLE_OPTIMIZE_DOMAIN_MAPPING': {'value':False,'dtype':'e'},
            'RECOMPUTE_POTENTIAL_IN_SNAPSHOT': {'value':False,'dtype':'e'},
            'CUDA': {'value':False,'dtype':'e'},
            'CUDA_INSTRUMENT': {'value':False,'dtype':'e'},
            'USE_DSDE': {'value':False,'dtype':'e'},
            'USE_NBC_FOR_IBARRIER': {'value':False,'dtype':'e'},
            'HUGEPAGES': {'value':False,'dtype':'e'},
            'DETAILEDTIMINGS': {'value':False,'dtype':'e'},
            'PERFORMANCE_TEST_SPARSE_MPI_ALLTOALL': {'value':False,'dtype':'e'},
            'TIMESTEP_OUTPUT_LIMIT': {'value':False,'dtype':'e'},
            'UPDATE_GRADIENTS_FOR_OUTPUT': {'value':False,'dtype':'e'},
            'REDUCE_FLUSH': {'value':False,'dtype':'e'},
            'OUTPUT_REFBHCOUNTER': {'value':False,'dtype':'e'},
            'OUTPUT_EVERY_STEP': {'value':False,'dtype':'e'},
            'GODUNOV_STATS': {'value':False,'dtype':'e'},
            'OUTPUT_CPU_CSV': {'value':False,'dtype':'e'},
            'OUTPUT_TASK': {'value':False,'dtype':'e'},
            'OUTPUT_TIMEBIN_HYDRO': {'value':False,'dtype':'e'},
            'OUTPUT_PRESSURE_GRADIENT': {'value':False,'dtype':'e'},
            'OUTPUT_DENSITY_GRADIENT': {'value':False,'dtype':'e'},
            'OUTPUT_VELOCITY_GRADIENT': {'value':False,'dtype':'e'},
            'OUTPUT_BFIELD_GRADIENT': {'value':False,'dtype':'e'},
            'OUTPUT_VERTEX_VELOCITY': {'value':False,'dtype':'e'},
            'OUTPUT_VERTEX_VELOCITY_DIVERGENCE': {'value':False,'dtype':'e'},
            'OUTPUT_VOLUME': {'value':False,'dtype':'e'},
            'OUTPUT_CENTER_OF_MASS': {'value':False,'dtype':'e'},
            'OUTPUT_SURFACE_AREA': {'value':False,'dtype':'e'},
            'OUTPUT_PRESSURE': {'value':False,'dtype':'e'},
            'OUTPUTPOTENTIAL': {'value':False,'dtype':'e'},
            'OUTPUTACCELERATION': {'value':False,'dtype':'e'},
            'OUTPUTTIMESTEP': {'value':False,'dtype':'e'},
            'OUTPUT_SOFTENINGS': {'value':False,'dtype':'e'},
            'OUTPUTGRAVINTERACTIONS': {'value':False,'dtype':'e'},
            'HAVE_HDF5': {'value':False,'dtype':'e'},
            'HDF5_FILTERS': {'value':False,'dtype':'e'},
            'OUTPUT_XDMF': {'value':False,'dtype':'e'},
            'OUTPUTCOOLRATE': {'value':False,'dtype':'e'},
            'OUTPUT_DIVVEL': {'value':False,'dtype':'e'},
            'OUTPUT_CURLVEL': {'value':False,'dtype':'e'},
            'OUTPUT_COOLHEAT': {'value':False,'dtype':'e'},
            'OUTPUT_VORTICITY': {'value':False,'dtype':'e'},
            'OUTPUT_CELL_SPIN': {'value':False,'dtype':'e'},
            'MEASURE_DISSIPATION_RATE': {'value':False,'dtype':'e'},
            'OUTPUT_MACHNUM': {'value':False,'dtype':'e'},
            'OUTPUT_TASK': {'value':False,'dtype':'e'},
            'DEBUG': {'value':False,'dtype':'e'},
            'DEBUG_ENABLE_FPU_EXCEPTIONS': {'value':False,'dtype':'e'},
            'CHECKSUM_DEBUG': {'value':False,'dtype':'e'},
            'RESTART_DEBUG': {'value':False,'dtype':'e'},
            'VERBOSE': {'value':False,'dtype':'e'},
            'HOST_MEMORY_REPORTING': {'value':False,'dtype':'e'},
            'VTUNE_INSTRUMENT': {'value':False,'dtype':'e'},
            'FORCETEST': {'value':False,'dtype':'f','default':0.001,'format':'%f'},
            'FORCETEST_TESTFORCELAW': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'DISK_POTENTIAL': {'value':False,'dtype':'e'},
            'DISK_MASS_M0': {'value':False,'dtype':'f','default':1.0,'format':'%f'},
            'DISK_SCALE_R0': {'value':False,'dtype':'f','default':1.0,'format':'%f'},
            'STATICNFW': {'value':False,'dtype':'e'},
            'NFW_C': {'value':False,'dtype':'i','default':12,'format':'%d'},
            'NFW_M200': {'value':False,'dtype':'f','default':100.0,'format':'%f'},
            'NFW_E': {'value':False,'dtype':'e'},
            'NFW_DARKFRACTION': {'value':False,'dtype':'f','default':0.87,'format':'%f'},
            'STATICISO': {'value':False,'dtype':'e'},
            'ISO_M200': {'value':False,'dtype':'f','default':100.0,'format':'%f'},
            'ISO_R200': {'value':False,'dtype':'f','default':160.0,'format':'%f'},
            'ISO_E': {'value':False,'dtype':'e'},
            'ISO_FRACTION': {'value':False,'dtype':'f','default':0.9,'format':'%f'},
            'STATICHQ': {'value':False,'dtype':'e'},
            'HQ_M200': {'value':False,'dtype':'f','default':186.015773,'format':'%f'},
            'HQ_C': {'value':False,'dtype':'f','default':10.0,'format':'%f'},
            'HQ_DARKFRACTION': {'value':False,'dtype':'f','default':0.9,'format':'%f'},
            'GROWING_DISK_POTENTIAL': {'value':False,'dtype':'e'},
            'DARKENERGY': {'value':False,'dtype':'e'},
            'TIMEDEPDE': {'value':False,'dtype':'e'},
            'RESCALEVINI': {'value':False,'dtype':'e'},
            'EXTERNALHUBBLE': {'value':False,'dtype':'e'},
            'TIMEDEPGRAV': {'value':False,'dtype':'e'},
            'DARKENERGY_DEBUG': {'value':False,'dtype':'e'},
            'SECOND_ORDER_ICS': {'value':False,'dtype':'e'},
            'LONGIDS': {'value':False,'dtype':'e'},
            'OFFSET_FOR_NON_CONTIGUOUS_IDS': {'value':False,'dtype':'e'},
            'GENERATE_GAS_IN_ICS': {'value':False,'dtype':'e'},
            'SPLIT_PARTICLE_TYPE': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'NTYPES_ICS': {'value':False,'dtype':'i','default':6,'format':'%d'},
            'VS_TURB': {'value':False,'dtype':'e'},
            'POWERSPEC_GRID': {'value':False,'dtype':'i','default':128,'format':'%d'},
            'AB_TURB': {'value':False,'dtype':'e'},
            'READ_LEGACY_ICS': {'value':False,'dtype':'e'},
            'EOS_DEGENERATE': {'value':False,'dtype':'e'},
            'EOS_COULOMB_CORRECTIONS': {'value':False,'dtype':'e'},
            'EOS_NSPECIES': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'RELAXOBJECT': {'value':False,'dtype':'e'},
            'RELAXOBJECT_COOLING': {'value':False,'dtype':'e'},
            'RELAXOBJECT_BINARY': {'value':False,'dtype':'e'},
            'PASSIVE_SCALARS': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'NUCLEAR_NETWORK': {'value':False,'dtype':'e'},
            'NETWORK_NSE': {'value':False,'dtype':'e'},
            'NETWORK_PARDISO': {'value':False,'dtype':'e'},
            'NETWORK_SCREENING': {'value':False,'dtype':'e'},
            'REACLIB1': {'value':False,'dtype':'e'},
            'NUCLEAR_NETWORK_DETONATE': {'value':False,'dtype':'e'},
            'EOS_OPAL': {'value':False,'dtype':'e'},
            'EOS_NSPECIES': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'RT_ENABLE': {'value':False,'dtype':'e'},
            'RT_COOLING_PHOTOHEATING': {'value':False,'dtype':'e'},
            'RT_ADVECT': {'value':False,'dtype':'e'},
            'RT_CGMETHOD': {'value':False,'dtype':'e'},
            'RT_SLOWLIGHT': {'value':False,'dtype':'e'},
            'RT_N_DIR': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'RT_COMBINE_N_DIR_IN_OUTPUT': {'value':False,'dtype':'e'},
            'RT_ALLOW_ABSORBING_CELLS': {'value':False,'dtype':'e'},
            'RT_SPREAD_SOURCE': {'value':False,'dtype':'e'},
            'RT_STELLAR_SOURCES': {'value':False,'dtype':'e'},
            'RT_HEALPIX_NSIDE': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'RT_INCLUDE_HE': {'value':False,'dtype':'e'},
            'SOURCE_PERIODIC': {'value':False,'dtype':'e'},
            'DO_NOT_MOVE_GAS': {'value':False,'dtype':'e'},
            'HYDROGEN_ONLY': {'value':False,'dtype':'e'},
            'SECOND_DERIVATIVES': {'value':False,'dtype':'e'},
            'SLOPE_LIMIT_HESSIANS': {'value':False,'dtype':'e'},
            'RECONSTRUCT_GRADIENTS': {'value':False,'dtype':'e'},
            'GLOBAL_VISCOSITY': {'value':False,'dtype':'e'},
            'USE_KINEMATIC_VISCOSITY': {'value':False,'dtype':'e'},
            'ALPHA_VISCOSITY': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'LOCAL_VISCOSITY': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'THERMAL_CONDUCTION': {'value':False,'dtype':'e'},
            'TRACER_DIFFUSION': {'value':False,'dtype':'e'},
            'CIRCUMSTELLAR': {'value':False,'dtype':'e'},
            'CIRCUMSTELLAR_WBOUNDARIES': {'value':False,'dtype':'e'},
            'CIRCUMSTELLAR_IRRADIATION': {'value':False,'dtype':'e'},
            'CIRCUMSTELLAR_SINKS': {'value':False,'dtype':'e'},
            'CIRCUMSTELLAR_PLANET_GROWTH': {'value':False,'dtype':'e'},
            'GRAVITY_FROM_STARS_PLANETS_ONLY': {'value':False,'dtype':'e'},
            'CENTRAL_MASS_POTENTIAL': {'value':False,'dtype':'e'},
            'BINARY_POTENTIAL': {'value':False,'dtype':'e'},
            'LOCALLY_ISOTHERM_DISK': {'value':False,'dtype':'e'},
            'SPECIAL_BOUNDARY': {'value':False,'dtype':'e'},
            'COAXIAL_BOUNDARIES': {'value':False,'dtype':'e'},
            'WINDTUNNEL': {'value':False,'dtype':'e'},
            'WINDTUNNEL_COORD': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'WINDTUNNEL_EXTERNAL_SOURCE': {'value':False,'dtype':'e'},
            'BOUNDARY_INFLOWOUTFLOW_MINID': {'value':False,'dtype':'i','default':10000000,'format':'%d'},
            'BOUNDARY_INFLOWOUTFLOW_MAXID': {'value':False,'dtype':'i','default':20000000,'format':'%d'},
            'BOUNDARY_REFL_FLUIDSIDE_MINID': {'value':False,'dtype':'i','default':30000000,'format':'%d'},
            'BOUNDARY_REFL_FLUIDSIDE_MAXID': {'value':False,'dtype':'i','default':30000000,'format':'%d'},
            'BOUNDARY_REFL_SOLIDSIDE_MINID': {'value':False,'dtype':'i','default':40000000,'format':'%d'},
            'BOUNDARY_REFL_SOLIDSIDE_MAXID': {'value':False,'dtype':'i','default':40000000,'format':'%d'},
            'BOUNDARY_REFL_ACTS_AS_SOURCE': {'value':False,'dtype':'e'},
            'BOUNDARY_STICKY_MINID': {'value':False,'dtype':'i','default':50000000,'format':'%d'},
            'BOUNDARY_STICKY_MAXID': {'value':False,'dtype':'i','default':60000000,'format':'%d'},
            'GFM': {'value':False,'dtype':'e'},
            'GFM_STELLAR_EVOLUTION': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'GFM_CONST_IMF': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'GFM_VARIABLE_IMF': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'GFM_PREENRICH': {'value':False,'dtype':'e'},
            'GFM_EXACT_NUMNGB': {'value':False,'dtype':'e'},
            'GFM_WINDS': {'value':False,'dtype':'e'},
            'GFM_WINDS_VARIABLE': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'GFM_WINDS_VARIABLE_HUBBLE': {'value':False,'dtype':'e'},
            'GFM_WINDS_HUBBLESCALING': {'value':False,'dtype':'e'},
            'GFM_WINDS_MASSSCALING': {'value':False,'dtype':'e'},
            'GFM_WIND_ENERGY_METAL_DEPENDENCE': {'value':False,'dtype':'e'},
            'GFM_WIND_ENERGY_METAL_DEPENDENCE_TANH': {'value':False,'dtype':'e'},
            'GFM_WINDS_STRIPPING': {'value':False,'dtype':'e'},
            'GFM_WINDS_THERMAL': {'value':False,'dtype':'e'},
            'GFM_WINDS_THERMAL_NEWDEF': {'value':False,'dtype':'e'},
            'GFM_BIPOLAR_WINDS': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'GFM_WINDS_LOCAL': {'value':False,'dtype':'e'},
            'GFM_STELLAR_FEEDBACK': {'value':False,'dtype':'e'},
            'GFM_PRIMORDIAL_RATES': {'value':False,'dtype':'e'},
            'GFM_COOLING_METAL': {'value':False,'dtype':'e'},
            'GFM_UVB_CORRECTIONS': {'value':False,'dtype':'e'},
            'GFM_AGN_RADIATION': {'value':False,'dtype':'e'},
            'GFM_STELLAR_PHOTOMETRICS': {'value':False,'dtype':'e'},
            'GFM_OUTPUT_MASK': {'value':False,'dtype':'s','default':'1+2+4+8+16+32+64+128','format':'%s'},
            'GFM_DUST': {'value':False,'dtype':'e'},
            'GFM_DUST_DESTMODE': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'GFM_DUST_SPUTTERING': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'GFM_CHECKS': {'value':False,'dtype':'e'},
            'GFM_DISCARD_ENRICHMENT_GRADIENTS': {'value':False,'dtype':'e'},
            'GFM_NORMALIZED_METAL_ADVECTION': {'value':False,'dtype':'e'},
            'GFM_OUTPUT_BIRTH_POS': {'value':False,'dtype':'e'},
            'GFM_CHEMTAGS': {'value':False,'dtype':'e'},
            'GFM_WINDS_SAVE_PARTTYPE': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'GFM_DISCRETE_ENRICHMENT': {'value':False,'dtype':'e'},
            'GFM_SPLITFE': {'value':False,'dtype':'e'},
            'GFM_RPROCESS': {'value':False,'dtype':'e'},
            'RADCOOL': {'value':False,'dtype':'e'},
            'RADCOOL_HOTHALO': {'value':False,'dtype':'e'},
            'RADCOOL_HOTHALO_METAL_BOOST': {'value':False,'dtype':'e'},
            'FM_SFR': {'value':False,'dtype':'e'},
            'FM_STAR_FEEDBACK': {'value':False,'dtype':'e'},
            'FM_STAR_FEEDBACK_KICK_TYPE': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'NON_STOCHASTIC_MOMENTUM_FEEDBACK': {'value':False,'dtype':'e'},
            'INJECT_INTO_SINGLE_CELL': {'value':False,'dtype':'e'},
            'DIRECT_MOMENTUM_INJECTION_FEEDBACK': {'value':False,'dtype':'e'},
            'OUTPUT_SF_PROBABILITY': {'value':False,'dtype':'e'},
            'TEST_SFR': {'value':False,'dtype':'e'},
            'USE_POLYTROPIC_EQSTATE': {'value':False,'dtype':'e'},
            'DELAYED_COOLING': {'value':False,'dtype':'e'},
            'SHUTOFFTIME_UPDATE': {'value':False,'dtype':'i','default':0,'format':'%d'},
            'DELAYED_COOLING_TURB': {'value':False,'dtype':'e'},
            'INSTANTANEOUS_DEPOSITION': {'value':False,'dtype':'e'},
            'EXPLICIT_COOLING': {'value':False,'dtype':'e'},
            'COMPUTE_SFR_FROM_H2': {'value':False,'dtype':'e'},
            'TEST_COOLING_METAL': {'value':False,'dtype':'e'},
            'OUTPUT_STELLAR_FEEDBACK': {'value':False,'dtype':'e'},
            'OUTPUT_MOLECULAR_FRACTION': {'value':False,'dtype':'e'},
            'OUTPUT_OPTICAL_DEPTH': {'value':False,'dtype':'e'},
            'RADPRESS_OPT_THIN': {'value':False,'dtype':'e'},
            'RADPRESS_OPT_THIN_LUMPERMASS': {'value':False,'dtype':'e'},
            'RADPRESS_OPT_THICK': {'value':False,'dtype':'e'},
            'FM_RADIATION_FEEDBACK': {'value':False,'dtype':'e'},
            'FM_RADIATION_FEEDBACK_DEBUG': {'value':False,'dtype':'e'},
            'FM_EARLY_STAR_FEEDBACK': {'value':False,'dtype':'e'},
            'FM_EARLY_STAR_FEEDBACK_KICK_TYPE': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'OUTPUT_EARLY_STELLAR_FEEDBACK': {'value':False,'dtype':'e'},
            'FM_MASS_WEIGHT_SN': {'value':False,'dtype':'e'},
            'FM_VAR_SN_EFF': {'value':False,'dtype':'e'},
            'MONOTONE_CONDUCTION': {'value':False,'dtype':'e'},
            'CONDUCTION_ISOTROPIC': {'value':False,'dtype':'e'},
            'CONDUCTION_ANISOTROPIC': {'value':False,'dtype':'e'},
            'CONDUCTION_CONSTANT': {'value':False,'dtype':'e'},
            'CONDUCTION_SATURATION': {'value':False,'dtype':'e'},
            'IMPLICIT_TI': {'value':False,'dtype':'e'},
            'SEMI_IMPLICIT_TI': {'value':False,'dtype':'e'},
            'RESTRICT_KAPPA': {'value':False,'dtype':'e'},
            'MULTIPLE_TIMESTEP': {'value':False,'dtype':'e'},
            'NON_LINEAR_SLOPE_LIMITERS': {'value':False,'dtype':'e'},
            'OTVET': {'value':False,'dtype':'e'},
            'OTVET_CHEMISTRY_PS2009': {'value':False,'dtype':'e'},
            'OTVET_CHEMISTRY_PS2011': {'value':False,'dtype':'e'},
            'OTVET_NOGRAVITY': {'value':False,'dtype':'e'},
            'OTVET_NOTMOVEGAS': {'value':False,'dtype':'e'},
            'OTVET_OUTPUT_ET': {'value':False,'dtype':'e'},
            'EDDINGTON_TENSOR_STARS': {'value':False,'dtype':'e'},
            'OTVET_MODIFY_EDDINGTON_TENSOR': {'value':False,'dtype':'e'},
            'OTVET_FLUXLIMITER': {'value':False,'dtype':'e'},
            'OTVET_CHANGEFLUXLIMITER': {'value':False,'dtype':'e'},
            'OTVET_FIXTIMESTEP': {'value':False,'dtype':'e'},
            'OTVET_COOLING_HEATING': {'value':False,'dtype':'e'},
            'OTVET_MULTI_FREQUENCY': {'value':False,'dtype':'e'},
            'OTVET_INCLUDE_HE': {'value':False,'dtype':'e'},
            'OTVET_SCATTER_SOURCE': {'value':False,'dtype':'e'},
            'OTVET_OUTPUT_SOURCEHSML': {'value':False,'dtype':'e'},
            'OTVET_CHECK_PHOTONCOUNT': {'value':False,'dtype':'e'},
            'OTVET_NOCOLLISION_IONIZATION': {'value':False,'dtype':'e'},
            'OTVET_SILENT': {'value':False,'dtype':'e'},
            'OTVET_MODIFY_EDDINGTON_TENSOR': {'value':False,'dtype':'e'},
            'TGSET': {'value':False,'dtype':'e'},
            'TGCHEM': {'value':False,'dtype':'e'},
            'HEALRAY': {'value':False,'dtype':'e'},
            'SINKS': {'value':False,'dtype':'e'},
            'SIDM': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'SIDM_CONST_CROSS': {'value':False,'dtype':'e'},
            'SIDM_STATES': {'value':False,'dtype':'i','default':2,'format':'%d'},
            'SIDM_REACTIONS': {'value':False,'dtype':'i','default':5,'format':'%d'},
            'SIDM_READ_ICS': {'value':False,'dtype':'e'},
            'SIDM_NO_SCATTER': {'value':False,'dtype':'e'},
            'SIDM_NO_TIMESTEP': {'value':False,'dtype':'e'},
            'SIDM_NO_KINEMATICS': {'value':False,'dtype':'e'},
            'SIDM_NO_NGB_SEL': {'value':False,'dtype':'e'},
            'SIDM_NO_MASSCHANGE': {'value':False,'dtype':'e'},
            'ISM': {'value':False,'dtype':'e'},
            'ISM_LOCAL_RADIATION_PRESSURE': {'value':False,'dtype':'e'},
            'ISM_LONG_RANGE_RADIATION_PRESSURE': {'value':False,'dtype':'e'},
            'ISM_HII_PHOTO_HEATING': {'value':False,'dtype':'e'},
            'ISM_H2_SFR': {'value':False,'dtype':'e'},
            'ISM_OUTPUT_FIELDS': {'value':False,'dtype':'s','default':'1+2+4','format':'%s'},
            'SHOCK_FINDER_BEFORE_OUTPUT': {'value':False,'dtype':'e'},
            'SHOCK_FINDER_ON_THE_FLY': {'value':False,'dtype':'e'},
            'SHOCK_FINDER_POST_PROCESSING': {'value':False,'dtype':'e'},
            'SHOCK_FINDER_AREPO': {'value':False,'dtype':'e'},
            'UNLIMITED_GRADIENTS': {'value':False,'dtype':'e'},
            'ZONE_JUMP_P': {'value':False,'dtype':'e'},
            'ZONE_JUMP_T': {'value':False,'dtype':'e'},
            'SHOCK_DIR_GRAD_T': {'value':False,'dtype':'e'},
            'SHOCK_JUMP_T': {'value':False,'dtype':'e'},
            'SURFACE_SPHERE_APPROX': {'value':False,'dtype':'e'},
            'SURFACE_ANGLE_APPROX': {'value':False,'dtype':'e'},
            'RESET_WRONG_JUMPS': {'value':False,'dtype':'e'},
            'RESET_WRONG_RHO_JUMPS': {'value':False,'dtype':'e'},
            'RESET_WRONG_P_JUMPS': {'value':False,'dtype':'e'},
            'OUTPUT_GRAVITY_FRACTION': {'value':False,'dtype':'e'},
            'SKIP_BORDER': {'value':False,'dtype':'e'},
            'ATOMIC_DM': {'value':False,'dtype':'e'},
            'STAR_INDEX': {'value':False,'dtype':'e'},
            'BINARYLOG': {'value':False,'dtype':'e'},
            'SPECIAL_SOFTENINGS': {'value':False,'dtype':'e'},
            'REDUCE_SOFTENINGS': {'value':False,'dtype':'e'},
            'ID_RGCORE': {'value':False,'dtype':'i','default':1000000000,'format':'%d'},
            'DMLOWESTTIMEBIN': {'value':False,'dtype':'e'},
            'DMFIXED': {'value':False,'dtype':'e'},
            'FLD': {'value':False,'dtype':'e'},
            'FLD_CONES': {'value':False,'dtype':'e'},
            'FLD_NCONES': {'value':False,'dtype':'i','default':12,'format':'%d'},
            'FLD_CONST_KAPPA': {'value':False,'dtype':'e'},
            'FLD_MARSHAK': {'value':False,'dtype':'e'},
            'FLD_HYPRE': {'value':False,'dtype':'e'},
            'FLD_HYPRE_IJ1': {'value':False,'dtype':'e'},
            'FLD_HYPRE_IJ2': {'value':False,'dtype':'e'},
            'HYPRE_PCG': {'value':False,'dtype':'e'},
            'FLD_MG': {'value':False,'dtype':'e'},
            'FLD_MG_GS': {'value':False,'dtype':'e'},
            'FLD_ANISOTROPIC_CIRCULAR': {'value':False,'dtype':'e'},
            'FLD_NO_TEMP_UPDATE': {'value':False,'dtype':'e'},
            'FLD_SILENT': {'value':False,'dtype':'e'},
            'FLD_TEST_BOUNDARY': {'value':False,'dtype':'e'},
            'FLD_UPPER_BOUNDARY_MINID': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'FLD_UPPER_BOUNDARY_MAXID': {'value':False,'dtype':'i','default':1000000,'format':'%d'},
            'FLD_LOWER_BOUNDARY_MINID': {'value':False,'dtype':'i','default':5000000,'format':'%d'},
            'FLD_LOWER_BOUNDARY_MAXID': {'value':False,'dtype':'i','default':6000000,'format':'%d'},
            'DG': {'value':False,'dtype':'e'},
            'DG_SET_IC_FROM_AVERAGES': {'value':False,'dtype':'e'},
            'DG_TEST_PROBLEM': {'value':False,'dtype':'e'},
            'DG_VERBOSE': {'value':False,'dtype':'e'},
            'DG_DEBUG': {'value':False,'dtype':'e'},
            'DEGREE_K': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'CALC_QUADRATURE_DATA': {'value':False,'dtype':'e'},
            'RIEMANN_HLLC': {'value':False,'dtype':'e'},
            'MINMOD_B': {'value':False,'dtype':'e'},
            'DISCONTINUITY_DETECTION': {'value':False,'dtype':'e'},
            'OUTPUT_DG_DISCONTINUITIES': {'value':False,'dtype':'e'},
            'OUTPUT_DG_INFLOW_BOUNDARIES': {'value':False,'dtype':'e'},
            'ANGLE_BOUND': {'value':False,'dtype':'e'},
            'CHARACTERISTIC_LIMITER': {'value':False,'dtype':'e'},
            'CONSERVED_LIMITER': {'value':False,'dtype':'e'},
            'POSITIVITY_LIMITER': {'value':False,'dtype':'e'},
            'FIX_MEAN_VALUES': {'value':False,'dtype':'e'},
            'CONDUCTION': {'value':False,'dtype':'e'},
            'GRACKLE': {'value':False,'dtype':'e'},
            'GRACKLE_H2': {'value':False,'dtype':'e'},
            'GRACKLE_D': {'value':False,'dtype':'e'},
            'GRACKLE_TAB': {'value':False,'dtype':'e'},
            'GRACKLE_ABUNDANCE_IN_ICS': {'value':False,'dtype':'e'},
            'GRACKLE_VERBOSE': {'value':False,'dtype':'e'},
            'SINK_PARTICLES': {'value':False,'dtype':'e'},
            'DUMP_SINK_PARTICLE_INFO': {'value':False,'dtype':'e'},
            'SINK_PARTICLES_SKIM_CELL_MASS': {'value':False,'dtype':'e'},
            'SINK_SIMPLEX': {'value':False,'dtype':'e'},
            'SINK_PARTICLES_VARIABLE_ACC_RADIUS': {'value':False,'dtype':'e'},
            'SINK_PARTICLES_FEEDBACK': {'value':False,'dtype':'e'},
            'SGCHEM': {'value':False,'dtype':'e'},
            'SGCHEM_NO_HIGHN_DCHEM': {'value':False,'dtype':'e'},
            'SGCHEM_NO_MOLECULES': {'value':False,'dtype':'e'},
            'CHEMISTRYNETWORK': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'JEANS_REFINEMENT': {'value':False,'dtype':'i','default':16,'format':'%d'},
            'NO_TARGET_MASS_CONDITION': {'value':False,'dtype':'e'},
            'STATIC_CHEMISTRY_TEST': {'value':False,'dtype':'e'},
            'ADVECTION_ONLY': {'value':False,'dtype':'e'},
            'CHEM_IMAGE': {'value':False,'dtype':'e'},
            'ABHE': {'value':False,'dtype':'e'},
            'SG_HEADER_FLAG': {'value':False,'dtype':'e'},
            'DEBUG_EVOLVE': {'value':False,'dtype':'e'},
            'DEBUG_RATE_EQ': {'value':False,'dtype':'e'},
            'DEBUG_PARTICLE_ID':{'value':False,'dtype':'i','default':1,'format':'%d'},
            'SGCHEM_TEMPERATURE_FLOOR':{'value':False,'dtype':'e'},
            'SGCHEM_ACCRETION_LUMINOSITY': {'value':False,'dtype':'e'},
            'SGCHEM_CONSTANT_ALPHAB': {'value':False,'dtype':'f','default':2.5e-13,'format':'%.2e'},
            'SGCHEM_DISABLE_COMPTON_COOLING': {'value':False,'dtype':'e'},
            'TREE_RAD': {'value':False,'dtype':'e'},
            'TREE_RAD_H2': {'value':False,'dtype':'e'},
            'TREE_RAD_CO': {'value':False,'dtype':'e'},
            'NSIDE': {'value':False,'dtype':'i','default':1,'format':'%d'},
            'OUTPUTCOL': {'value':False,'dtype':'e'},
            'TREE_RAD_VEL': {'value':False,'dtype':'e'},
            'SGCHEM_RT': {'value':False,'dtype':'e'},
            'SIMPLEX': {'value':False,'dtype':'e'},
            'SX_CHEMISTRY': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'SX_NDIR': {'value':False,'dtype':'i','default':84,'format':'%d'},
            'SX_SOURCES': {'value':False,'dtype':'i','default':5,'format':'%d'},
            'SX_NUM_ROT': {'value':False,'dtype':'i','default':3,'format':'%d'},
            'SX_HYDROGEN_ONLY': {'value':False,'dtype':'e'},
            'SX_DISPLAY_STATS': {'value':False,'dtype':'e'},
            'SX_DISPLAY_TIMERS': {'value':False,'dtype':'e'},
            'SX_DISPLAY_TIMERS_SITE': {'value':False,'dtype':'e'},
            'SX_DISPLAY_MEMORY': {'value':False,'dtype':'e'},
            'SX_OUTPUT_IMAGE': {'value':False,'dtype':'e'},
            'SX_OUTPUT_IMAGE_ALL': {'value':False,'dtype':'e'},
            'SX_OUTPUT_FLUX': {'value':False,'dtype':'e'},
            'SX_RECOMBINE': {'value':False,'dtype':'e'},
            'SX_RADIATION_PRESSURE': {'value':False,'dtype':'e'},
            'SX_FLOAT_PRECISION': {'value':False,'dtype':'e'},
            'SX_PP_ZERO_SNAPSHOT': {'value':False,'dtype':'e'},
            'SX_SKIP_RADIUS': {'value':False,'dtype':'e'},
            'MAX_VARIATION_TOLERANCE': {'value':False,'dtype':'i','default':100,'format':'%d'}
        }

        if fileName!=None:
            self.read(fileName,show=show,notes=notes)

    def parse(self, rmGroups=[], rmParams=[], cmGroups=[], cmParams=[]):
        output = ''
        for group in self.groups:
            if group['id'] in rmGroups: continue
            gOutput = ''
            for param in group['params']:
                if param in rmParams: continue
                if self.params[param]['value'] is not False:
                    if (param in cmParams) or (group['name'] in cmGroups):
                        gOutput += "# "
                    if (self.params[param]['dtype']=='e'):
                        gOutput += "%s"%(param)
                    else:
                        gOutput += "%s="%(param) 
                        gOutput += self.params[param]['format']%self.params[param]['value'] 
                    if 'note' in self.params[param]:
                        gOutput += '   % '+self.params[param]['note']
                    gOutput += '\n'
                    
            if gOutput!='':
                output += "#----------------------------- %s\n"%group['name'] + gOutput + "\n";
        return output
        
    def read(self,fileName,show=False,notes=False):
        self.fileName = fileName
        with open(fileName,'r') as f:
            content = f.read()
        lines = content.split("\n")
        for line in lines:
            m = re.match("([_A-Z0-9]+)[=]?([\.e\+\-0-9]*)\s*[\#]?(.*)",line)  ## DEBUG: in python 3 \e changed to e?? meh!

            if m==None: continue
            note = m.group(3) if notes else None
            self.setValue(m.group(1),m.group(2),note)
        
        if show==True:
            print( self.parse() )

    def write(self,fileName,rmGroups=[],rmParams=[],cmGroups=[],cmParams=[],meshrelax=False):
        if meshrelax:
            self.setValue('MESHRELAX',True)    # set meshrelax
            rmGroups.extend([10])              # remove normal images
            rmParams.extend(['CHEM_IMAGE','SX_OUTPUT_IMAGE','SX_OUTPUT_IMAGE_ALL']) # remove chem images
        output = """#!/bin/bash            # this line only there to enable syntax highlighting in this file 

##################################################
#  Enable/Disable compile-time options as needed #
##################################################

"""
        output += self.parse(rmGroups=rmGroups,rmParams=rmParams,cmGroups=cmGroups,cmParams=cmParams)
        with open(fileName,'w') as f:
            f.write(output)

    def _setValue(self,param,value=None,note=None):
        if value is False:
            self.params[param]['value']=False
            return
        if param in self.params:
            dtype = self.params[param]['dtype']
            if (dtype=='e'):
                value = True
            else:
                if value is None or value is True: 
                    value = self.params[param]['default']
                if (dtype=='i'):
                    value = 0 if value=='' else int(value)
                elif (dtype=='f'):
                    value = float(value)
                elif (dtype=='s'):
                    value = str(value)
            self.params[param]["value"] = value
        else:
            if value is None or value is True: value = ''
            apy.shell.printc("Unknown parameter '%s' (config.py)\nIn file: %s"%(param,self.fileName),'r')
            self.params[param] = {'dtype':'s','default':'','format':'%s','value':str(value)}
            self.groups[-1]['params'].append(param)
        if note is not None and note!='':
            self.params[param]['note'] = note
    def setValue(self,param,value=None,note=None):
        if isinstance(param,dict):
            for p,v in param.items():
                self._setValue(p,v)
        else:
            self._setValue(param,value,note)

    def _getValue(self,param):
        return self.params[param]['value']
    def getValue(self,param):
        if isinstance(param,(str,int,float)):
            return self._getValue(param)
        else:
            return [ self._getValue(value) for value in param ]

    def getDtype(self,param):
        return self.params[param]['dtype']

    def formatValue(self,param,value=None):
        if value is None:
            value = self.params[param]['value']
        if self.params[param]['dtype']=='e':
            return True if value else False
        elif value is False:
            return False
        else:
            return self.params[param]['format']%value

def configCompare(fname,gname):
    f = apy.files.config(fname)
    g = apy.files.config(gname)
    output = apy.shell.textc('Comparing config files\nFile 1: %s\nFile 2: %s\n'%(fname,gname))
    for group in f.groups:
        gOutput = ''
        for param in group['params']:
            if f.params[param]['value'] or g.params[param]['value']:
                # using unicode tick/cross marks listed at: https://apps.timwhitlock.info/emoji/tables/unicode
                fval = f.getValue(param)
                #if fval is True:    fval = '\xE2\x9C\x94'
                #elif fval is False: fval = '\xE2\x9C\x96'
                gval = g.getValue(param)
                #if gval is True:    gval = '\xE2\x9C\x94' 
                #elif gval is False: gval = '\xE2\x9C\x96'
                line = "%-40s %-30s %-30s \n"%(param,fval,gval)
                gOutput += line if fval==gval else apy.shell.textc(line,'r')
        if gOutput!='':
            output += "%%---- %s\n"%group['name'] + gOutput + "\n";
    print( output )
